-- Generated from the 12 district pages (dist/d1.html to dist/d12.html) as they were on 2026-10-04.
-- Run after schema.sql.

insert into public.districts (slug, name, headline, description) values ('lahaul-spiti', 'Lahaul & Spiti', 'Two valleys. One tough kind of calm.', 'Lahaul-Spiti is the highest and most remote region of Himachal, where nature sets the terms of life. Lahaul is greener and faster, with short summers and urgent work rhythms. Potato harvests are crucial, and one early snowfall can ruin an entire year. The Atal Tunnel has brought major changes, better access to hospitals and winter travel, but also crowds, waste, and a loss of the old open-door culture.


Spiti is quieter and harsher. Winters are long, and life centers around one warm room, stored food, and careful preparation. Villages come alive indoors with games, stories, and slow time. Water is strictly shared under the Churpon’s rules, and faith remains simple and practical, monasteries in Spiti, devtas in Lahaul, coexisting without rivalry.');
insert into public.recommended_spots (district_slug, name, body, position) values ('lahaul-spiti', 'Spiti winter evenings (bukhari + Cholo culture)', 'If you visit Spiti in winter, the real experience is indoors. People gather around the bukhari, share endless cups of tea, and play Cholo, a dice game, for hours. This is how villages spend long nights when everything outside is still.', 0);
insert into public.recommended_spots (district_slug, name, body, position) values ('lahaul-spiti', 'Udaipur (Trilokinath Temple)', 'This is a rare place where Hindus and Buddhists both come to pray. Take a slow walk, sit quietly for a few minutes, and you’ll understand why locals have so much respect for it.', 1);
insert into public.recommended_spots (district_slug, name, body, position) values ('lahaul-spiti', 'Ladarcha Fair (Kaza side)', 'Today, it’s a cultural fair, but people remember it as Spiti’s old trade meeting spot. If you visit during the season, you’ll find wool, local goods, dances, and the strong spirit of the border valley all together.', 2);
insert into public.recommended_spots (district_slug, name, body, position) values ('lahaul-spiti', 'Sissu + Ghepan Peak view', 'No one climbs Ghepan Peak; you admire it from the valley. Locals see it as a protective mountain, especially in years with heavy snow. The best views are from Sissu in the early morning.', 3);
insert into public.recommended_spots (district_slug, name, body, position) values ('lahaul-spiti', 'Mani stone walls (Tabo / Key / Pin side)', 'Tourists come for monasteries, but these walls show everyday Spiti. They’re right on village routes, so you can see them without trekking. Quiet, beautiful, and very “local life”.', 4);

insert into public.districts (slug, name, headline, description) values ('kinnaur', 'Kinnaur', 'Life follows the land.', 'Kinnaur is not a place you rush through. The land changes fast here: orchards, rock, then high cold stretches, and people move with it. Villages sit close to mountains and rivers, and Kinner Kailash is always there, watching over daily life. People work in apple orchards, tend animals, and follow customs that mix Hindu devta worship with Buddhist traditions. Nothing feels forced. The terrain decides the pace, the weather decides the day, and people adjust without complaint. Kinnaur feels quiet, serious, and deeply rooted, because living here has always required attention and respect.');
insert into public.recommended_spots (district_slug, name, body, position) values ('kinnaur', 'Roghi (near Kalpa)', 'This is a quiet village with narrow stairways and old wooden doors. Visit early in the morning, when mist still covers the Sutlej valley.', 0);
insert into public.recommended_spots (district_slug, name, body, position) values ('kinnaur', 'Kamru Fort (Sangla side)', 'This wooden fort-temple complex sits above the valley. Most people stop at the gate, but you should go inside to truly experience it.', 1);
insert into public.recommended_spots (district_slug, name, body, position) values ('kinnaur', 'Rakcham Meadows', 'The riverbank between Sangla and Chitkul is wide and open, filled with wildflowers and birds during summer. It feels calm and unhurried.', 2);
insert into public.recommended_spots (district_slug, name, body, position) values ('kinnaur', 'Khab Confluence', 'This is where the Spiti river meets the Sutlej. The land drops steeply here, and the joining of the rivers marks the start of upper Kinnaur.', 3);
insert into public.recommended_spots (district_slug, name, body, position) values ('kinnaur', 'Chilgoza Woods (Nichar belt)', 'These rare pine forests produce valuable pine nuts. Entry is limited to certain times and locals, so always ask before you go in.', 4);
insert into public.recommended_spots (district_slug, name, body, position) values ('kinnaur', 'Yula Kanda (near Sangla)', 'This local pilgrimage trail leads to a high-altitude lake and a small Krishna temple. The place is quiet and has deep roots in local tradition.', 5);

insert into public.districts (slug, name, headline, description) values ('chamba', 'Chamba', 'Old ways, held close.', 'Chamba reminds you of Himachal before things sped up. Life here still moves with the seasons, local songs, and the land. People farm on terraces, walk long distances without fuss, and gather at temples and fairs that have mattered for generations. In winter, roads close; during the monsoon, rains cut off valleys. This distance has helped Chamba stay true to itself. It’s quieter, slower, and follows its own steady rhythm.');
insert into public.recommended_spots (district_slug, name, body, position) values ('chamba', 'Saho Hanuman Temple', 'This village temple, with its narrow lanes, ringing bells, and daily prayers, gives you a real sense of local life.', 0);
insert into public.recommended_spots (district_slug, name, body, position) values ('chamba', 'Chhatrari Devi Temple', 'This old hill shrine sits among cedar trees and springs. Quiet, powerful, and still deeply respected.', 1);
insert into public.recommended_spots (district_slug, name, body, position) values ('chamba', 'Bhalei Mata Temple', 'You reach it by walking through forest paths, and it gets especially busy during Navratri. The views of Dalhousie from here are breathtaking.', 2);
insert into public.recommended_spots (district_slug, name, body, position) values ('chamba', 'Bhandal Valley', 'You’ll find apple orchards, pine forests, grazing cattle, and long stretches of silence here. It’s beautiful in summer and completely still in winter.', 3);
insert into public.recommended_spots (district_slug, name, body, position) values ('chamba', 'Bharmour', 'Here, temple courtyards fill with life, shepherds return home, and it’s where the Manimahesh Yatra begins.', 4);
insert into public.recommended_spots (district_slug, name, body, position) values ('chamba', 'Pangi Valley', 'This place is remote, shaped by the seasons, and challenging. Life is tough here, but people are self-reliant and their way of living hasn’t changed over time.', 5);

insert into public.districts (slug, name, headline, description) values ('kullu', 'Kullu', 'Devta land, everyday hustle.', 'Kullu looks like a valley people “visit”, but for locals it’s a place they negotiate with daily: weather, roads, orchards, and devtas. Life here runs on two calendars: the one on your phone, and the one decided by the village deity through the gur (oracle). The Beas keeps the main valley busy from Bhuntar to Manali, but the real Kullu lives a little away from the highway in side valleys where kath-kuni homes still stand, old traditions still matter, and silence is treated like good manners. Tourism is loud, yes, but the valley itself is not.');
insert into public.recommended_spots (district_slug, name, body, position) values ('kullu', 'Lug Valley (Tiun–Peeni side)', 'You’ll find rough roads, peaceful villages, and old wooden houses here. This is the real Kullu, slow, traditional, and authentic.', 0);
insert into public.recommended_spots (district_slug, name, body, position) values ('kullu', 'Garsa Valley (Bhalan belt)', 'It’s a lush, hidden spot that most visitors miss. You’ll see forests, terraced fields, and village life that still feels untouched.', 1);
insert into public.recommended_spots (district_slug, name, body, position) values ('kullu', 'Kath-Kuni homes (Banjar/Naggar side)', 'These traditional houses are built with layers of wood and stone. When there’s an earthquake, the wood lets the house move a bit instead of breaking like cement buildings do. That’s why many Kath-Kuni homes handle earthquakes better. They’re designed for the mountains, not just for appearance.', 2);
insert into public.recommended_spots (district_slug, name, body, position) values ('kullu', 'Serolsar Lake (Jalori side)', 'For locals, this lake is sacred, not just a place for photos. You’ll notice how people keep it quiet and respectful.', 3);
insert into public.recommended_spots (district_slug, name, body, position) values ('kullu', 'Lingri season (May–June)', 'If you’ve been here before, you’ll know about this. In spring, locals cook fern sabzi. It’s fresh, local, and healthy. If you visit Kullu at this time, be sure to try lingri ki bhaaji.', 4);
insert into public.recommended_spots (district_slug, name, body, position) values ('kullu', 'A real Kullu rule', 'Never whistle at night. People here believe it brings bad energy from the forests, and everyone takes this seriously.', 5);

insert into public.districts (slug, name, headline, description) values ('shimla', 'Shimla', 'Not a mall town. A Whole power district.', 'Most people think Shimla is Mall Road. That’s the beginner version. Shimla is the capital district and holds a lot of responsibility for Himachal. It’s home to government offices, major hospitals, and the systems that support every other town in the state. Shimla’s main role is to keep everything working smoothly.


Yes, Shimla city gets crowded. But calling Shimla “crowded” misses the point. The city is busy because it matters; it’s the capital, the nerve centre, and people rely on it.

Most outsiders don’t realize that Shimla district is much bigger than just the city. The real Shimla includes orchard belts, forest ridges, and villages like Narkanda, Rohru, Kotkhai, Jubbal, Rampur, and Chopal. In these places, the air is sharper, the roads are rougher, and Himachal feels untouched again.');
insert into public.recommended_spots (district_slug, name, body, position) values ('shimla', 'Shali Tibba trek (Khatnol side)', 'The highest peak above Shimla. A steady cedar-forest walk, best for sunrise. At the top sits a small Bhimakali temple and a silence that feels serious. Carry your waste back.', 0);
insert into public.recommended_spots (district_slug, name, body, position) values ('shimla', 'Cheog (Fagu side)', 'This peaceful apple village is where life in Shimla slows down. You’ll find orchards, simple homestays, and the quiet village atmosphere that draws people to Himachal.', 1);
insert into public.recommended_spots (district_slug, name, body, position) values ('shimla', 'Narkanda (skiing + snow belt)', 'This is where Shimla district becomes wild and snowy. In winter, locals visit for snow days, simple mountain living, and skiing. Visit early in the morning when the roads are empty and the forests feel magical.', 2);
insert into public.recommended_spots (district_slug, name, body, position) values ('shimla', 'Kotgarh (apple valley life)', 'This is the part of Shimla many people overlook: the true apple belt. You’ll see long orchard roads, farmhouses, apple packing sheds, and a peaceful valley atmosphere. If you’re looking for the old Himachal feel, Kotgarh offers it naturally.', 3);
insert into public.recommended_spots (district_slug, name, body, position) values ('shimla', 'Rampur (Bushahr side)', 'Its an old trade town on the Sutlej, built for business rather than tourism. Visit during the Lavi Fair season to experience Shimla’s historic trading spirit.', 4);
insert into public.recommended_spots (district_slug, name, body, position) values ('shimla', 'Rohru (Pabbar side)', 'Here, you’ll discover trout streams, apple orchards, and a strong local way of life. This area of Shimla district is quieter, colder, and far more authentic than most people imagine.', 5);

insert into public.districts (slug, name, headline, description) values ('kangra', 'Kangra', 'So many worlds, quietly together.', 'Kangra is open and spacious. Life flows between tea gardens, old forts, monasteries, markets, and quiet farming villages. One side of the district faces the plains, while the other looks up at the Dhauladhar mountains. People here juggle farming, small businesses, government jobs, and tourism, which shifts with the seasons. Unlike other districts, Kangra doesn’t feel crowded. Instead, it offers space, variety, and the feeling that many different worlds exist together in peace.');
insert into public.recommended_spots (district_slug, name, body, position) values ('kangra', 'Masroor Rock-Cut Temples', 'These stone temples are carved from a single rock and set away from the main road. Locals visit for peaceful darshan and to relax by the water tank in front.', 0);
insert into public.recommended_spots (district_slug, name, body, position) values ('kangra', 'Bathu Ki Ladi', 'Most of the year, these old temples are underwater. When the water goes down, they slowly come into view again. Visiting them is a seasonal experience that feels truly local.', 1);
insert into public.recommended_spots (district_slug, name, body, position) values ('kangra', 'Neugal & Gunehar side', 'These are short walking paths near Palampur and Bir where locals go for evening strolls and small picnics. They are simple spots, not typical tourist attractions.', 2);
insert into public.recommended_spots (district_slug, name, body, position) values ('kangra', 'Sidhbari & Gopalpur', 'The Chinmaya Mission temple in Sidhbari looks out at the mountains. Gopalpur remains peaceful, with walking trails, open fields, and Sunday visitors from nearby towns.', 3);
insert into public.recommended_spots (district_slug, name, body, position) values ('kangra', 'Andretta village', 'This quiet art village is known for pottery and a relaxed pace of life. It has workshops, old houses, and a creative calm that has stayed the same over time.', 4);
insert into public.recommended_spots (district_slug, name, body, position) values ('kangra', 'Pragpur–Garli belt', 'These heritage villages have old havelis and narrow streets. Families still live here, run their shops, and carry on with daily life surrounded by history.', 5);

insert into public.districts (slug, name, headline, description) values ('sirmaur', 'Sirmaur', 'Hills that start like plains, and end at Shiva’s doorstep.', 'Sirmaur marks the southern entrance to Himachal. It begins in the warm plains of Paonta, where both the weather and the pace of life feel Punjabi-Haryanvi. From there, the land gently rises into pine forests, orchards, and areas rich in old mountain traditions.


This district has a very specific vibe: it shifts every 30–40 km. One side runs on factories, highways, and the Yamuna belt. The other side runs on village devtas, seasonal fairs, and long pilgrim walks to peaks like Churdhar.');
insert into public.recommended_spots (district_slug, name, body, position) values ('sirmaur', 'Churdhar (Shiva peak walk)', 'Not a casual trek. This is a proper old-school Himachali pilgrimage. People still walk for days to reach the top and pay respect at the Shiva temple. Go if you want to see mountain faith in its real form.', 0);
insert into public.recommended_spots (district_slug, name, body, position) values ('sirmaur', 'Renuka Valley (Dadahu–Renuka Ji)', 'This is the heart of Sirmaur. There is a sacred lake, a temple beside the water, and a valley filled with fields and a slower pace of life. If you come during the Renuka Fair after Diwali, you will see the whole district gather as if it is a yearly tradition.', 1);
insert into public.recommended_spots (district_slug, name, body, position) values ('sirmaur', 'Rajgarh (Peach Valley belt)', 'This area of Sirmaur is famous for its orchards, with peaches, plums, apples, and fresh mornings. It is greener, cooler, and more peaceful than most people expect from the lower parts of Himachal.', 2);
insert into public.recommended_spots (district_slug, name, body, position) values ('sirmaur', 'Trans-Giri (Shillai–Sangrah side)', 'This area is remote, with a strong culture and a different pace of life. There are weekly markets, terraced fields, walnut trees, and villages that still keep old customs. If you want to see the true interior of Sirmaur, this is the place.', 3);
insert into public.recommended_spots (district_slug, name, body, position) values ('sirmaur', 'Trilokpur (Bala Sundari temple)', 'It gets busy during Navratri and remains powerful all year. This is a place where belief runs deep, and the crowd is made up of locals, not tourists.', 4);

insert into public.districts (slug, name, headline, description) values ('mandi', 'Mandi', 'Trade town. Temple lanes.', 'People call Mandi Chhoti Kashi because it has many temples. That part is true. But there’s more to Mandi’s identity than just its temples. This district has long been the market heart of Himachal. The name “Mandi” itself means marketplace. Set between the hills and plains, it has always been a crossroads for trade, farming, and travel.


The Beas River flows through the district and is its lifeline. Mandi town grew along its banks, with old bridges, ghats, and narrow bazaar lanes. Beyond the town, valleys like Seraj, Karsog, and Chuhar are quieter and hold onto their traditional ways. Here’s something most visitors don’t know: Mandi has rock salt mines in Guma and Drang. In the past, Mandyali salt was so valuable it was used like currency.');
insert into public.recommended_spots (district_slug, name, body, position) values ('mandi', 'Old Mandi Bazaar + Kachori trail', 'Take a stroll through Sunken Garden, Seri Bazaar, and Chohata. Afterward, try the local kachori, which is crushed and served in spicy curry. This is the true flavor of the town.', 0);
insert into public.recommended_spots (district_slug, name, body, position) values ('mandi', 'Victoria Bridge + Panchvaktra Sangam', 'Take an evening walk on the 1877 bridge. From here, you get a clear view of the Beas and the Panchvaktra temple where the rivers meet. It’s simple, peaceful, and truly feels like Mandi.', 1);
insert into public.recommended_spots (district_slug, name, body, position) values ('mandi', 'Thachi Valley walk (Bitthu Narayan → Ashu Dev)', 'This quiet valley of apple and cedar trees is often missed by travelers. The walk leads to the Ashu Dev temple and the Ashu Alli waterfall, a clean and sacred spot that locals hold in high regard.', 2);
insert into public.recommended_spots (district_slug, name, body, position) values ('mandi', 'Kunhoo Dar viewpoint (Karsog side)', 'Locals love this wide ridge viewpoint for its open views, strong winds, and peaceful lack of crowds.', 3);
insert into public.recommended_spots (district_slug, name, body, position) values ('mandi', 'Chattri + Magru Mahadev', 'This is one of the best Kath-Kuni temples in the district. The wood-and-stone structure, along with its carvings, is worth seeing, and the nearby sacred forest feels untouched.', 4);

insert into public.districts (slug, name, headline, description) values ('solan', 'Solan', 'Not a stop. The district that builds Himachal.', 'Solan is one of Himachal’s most active districts. It brings together the industrial muscle of Baddi, the student life of Nauni, Waknaghat, and Shoolini, and the quiet discipline of old cantonments like Kasauli, Dagshai, and Sabathu.

This district has a strong farming base, with wide fields, vegetables, seasonal crops, mixed farming, and its famous mushrooms and tomatoes. In many areas, you’ll see working farmland that doesn’t look like the usual tourist Himachal. This is Himachal’s productive side: steady, practical, and always moving.');
insert into public.recommended_spots (district_slug, name, body, position) values ('solan', 'Karol ka Tibba (Solan side)', 'This is Solan’s real hill test. It’s a steady climb through quiet pine and deodar trees, with a view that makes you forget the highway. Go early in the morning. If you’re lucky, you’ll see clouds below you like a blanket.', 0);
insert into public.recommended_spots (district_slug, name, body, position) values ('solan', 'Jatoli Shiv Temple (Solan city) + tea outside', 'Don’t just visit the temple. Sit outside for ten minutes. The bells, the wind, and the local crowd moving in their own rhythm give you the real Solan vibe. Grab some tea from the nearby stalls. Simple and perfect.', 1);
insert into public.recommended_spots (district_slug, name, body, position) values ('solan', 'Phantom Hill (Solan ridge)', 'Locals don’t oversell this place. It’s a quiet ridge where you can park, take a short walk, and let your mind relax. It’s best at sunset or on foggy mornings. There’s no market noise and no tourist crowds.', 2);
insert into public.recommended_spots (district_slug, name, body, position) values ('solan', 'Barog railway station + tunnel walk vibe', 'Barog isn’t just a destination; it’s a mood. The misty station, old rail feel, scent of pine, and the energy around the tunnel all add to the charm. Even if you do nothing else, just stand here with chai and watch the trains go by.', 3);
insert into public.recommended_spots (district_slug, name, body, position) values ('solan', 'Dagshai (early morning walk)', 'Come here for a calm, old-world morning. You’ll find stone lanes, British-era barracks, a school town feel, and a quiet you won’t get in crowded hill stations. It’s perfect for slow walkers and anyone who likes history without the fuss of a museum.', 4);
insert into public.recommended_spots (district_slug, name, body, position) values ('solan', 'Sabathu (cantonment town)', 'Sabathu is small, disciplined, and has a unique peace. Walk through the old cantonment areas, notice how different it feels from the rest of Himachal, and try something simple to eat in the bazaar. Sabathu is underrated, which is why it still feels authentic.', 5);
insert into public.recommended_spots (district_slug, name, body, position) values ('solan', 'Kandaghat → Chail road (drive for pine and deodar forests)', 'This road shows the softer side of Solan. Stop anywhere safe, take a breath, and you’ll notice how the forests change. It’s one of the best drives for that classic Himachal feeling without having to travel far.', 6);
insert into public.recommended_spots (district_slug, name, body, position) values ('solan', 'Aunty ka Dhaba (Chail side)', 'This place isn’t about taking food photos. It’s about comfort. You eat, relax, and leave feeling cared for. Go when you’re hungry. Don’t worry about the menu—just eat what’s fresh.', 7);

insert into public.districts (slug, name, headline, description) values ('bilaspur', 'Bilaspur', 'Seven hills. Steady life.', 'Bilaspur is a quieter side of Himachal, without the hustle and bustle. Life here revolves around hills, water, temples, fairs, and evening walks by the lake. There aren’t crowds or cafés competing for attention. Instead, you’ll find open spaces, wide skies, and a town that feels like home. Many people come here just passing through, but often end up staying longer than they expected.');
insert into public.recommended_spots (district_slug, name, body, position) values ('bilaspur', 'Gobind Sagar Lake', 'The lake has still waters, wide horizons, fishing boats, and sunsets that make you slow down. Boating here is peaceful and not rushed.', 0);
insert into public.recommended_spots (district_slug, name, body, position) values ('bilaspur', 'Bandla Hill', 'You get open views, can watch paragliders in the sky, and see how Bilaspur quietly stretches out below.', 1);
insert into public.recommended_spots (district_slug, name, body, position) values ('bilaspur', 'Bahadurpur Hill', 'The highest point of the district, known for deodar forests, cool air, fort ruins and wide views. It’s a place locals respect, and one that feels best when visitors do the same, and it''s not meant for careless crowds.', 2);
insert into public.recommended_spots (district_slug, name, body, position) values ('bilaspur', 'Rukmani Kund', 'This is a small sacred pond in the hills. It’s peaceful, shaded, and the kind of place people come to sit for a while and do nothing. Locals treat it with care, so keep it clean and leave the calm behind for the next visitor.', 3);
insert into public.recommended_spots (district_slug, name, body, position) values ('bilaspur', 'Kandrour Bridge', 'A solid, old bridge over the Sutlej. Not flashy, just impressive when you stand under it.', 4);
insert into public.recommended_spots (district_slug, name, body, position) values ('bilaspur', 'Shahtalai', 'This is an important pilgrimage site connected to Baba Balak Nath Ji. Locals and devotees visit it throughout the year.', 5);

insert into public.districts (slug, name, headline, description) values ('hamirpur', 'Hamirpur', 'Work, study, return.', 'Hamirpur might look small on the map, but life here is always busy. People move between work, classes, and home all day. The roads link nearly every village, so nowhere feels out of reach. Mornings are full of people heading to offices and coaching centers. By evening, it’s time for chai: friends meet up, students gather at cafés, and you see familiar faces everywhere.

Education is a big part of life here. Coaching centers, colleges, and NIT keep Hamirpur lively and full of young people. Village life is always close by, too. Many locals have army or government backgrounds, and even after retirement, they stay active. They work in their fields, catch up with friends at favorite spots, or join the many seven-day Bhagwat kathas held throughout the year. In Hamirpur, it’s common to spend one day at the office and the next in the fields, just because you feel like it.');
insert into public.recommended_spots (district_slug, name, body, position) values ('hamirpur', 'Sujanpur Chaugan (sunrise)', 'Take an early walk and watch kite flyers as the mist rises from the Beas. It’s peaceful before the town wakes up.', 0);
insert into public.recommended_spots (district_slug, name, body, position) values ('hamirpur', 'Narbadeshwar Temple Murals (Sujanpur)', 'The old wall paintings here are rich in detail. If you go with a local, you’ll spot things you might otherwise miss.', 1);
insert into public.recommended_spots (district_slug, name, body, position) values ('hamirpur', 'Nadaun River Ghats', 'Enjoy evening tea while anglers wait patiently and the Beas flows wide and calm.', 2);
insert into public.recommended_spots (district_slug, name, body, position) values ('hamirpur', 'Markandeya Kund (Dera Parol)', 'There’s a shaded spring near the temple that’s quiet, cool, and perfect for slowing down.', 3);
insert into public.recommended_spots (district_slug, name, body, position) values ('hamirpur', 'Awah Devi Ridge', 'You’ll find open views in every direction, sharp sunsets, roadside tea, and fresh, clear air.', 4);
insert into public.recommended_spots (district_slug, name, body, position) values ('hamirpur', 'Sujanpur Fort Hill', 'The palace ruins above the town are great for walks and offer long views over the river.', 5);

insert into public.districts (slug, name, headline, description) values ('una', 'Una', 'Himachal’s plain district. With hills waiting in the background.', 'Una stands out from the rest of Himachal, and that’s what makes it special. It has its own charm. Here, the land gets warmer, flatter, and life moves a bit quicker. You’ll find long fields in the Swan valley, busy roads, dhabas, truck routes, factories, and a bazaar that runs on routine

But Una isn’t just plain. Go towards Bangana and Chintpurni, and you’ll start to feel the hills, slow-paced villages, ridge viewpoints, forest patches, and old shrines that locals truly value. Una is a place where cultures blend easily. The food has a Punjabi touch, but the faith and manners remain Himachali.

So, Una isn’t a “tourist district.” It’s a real place: hardworking, practical, and closely tied to its temples, deras, and local traditions.');
insert into public.recommended_spots (district_slug, name, body, position) values ('una', 'Chintpurni Temple (Amb side)', 'Yes, it’s famous, but for locals, it’s personal. People come here for life events, not just darshan. If you visit during Navratri, you’ll understand how big this faith really is.', 0);
insert into public.recommended_spots (district_slug, name, body, position) values ('una', 'Dera Baba Barbhag Singh (Mairi)', 'A powerful Sikh dera with a strong belief culture around healing and blessings. During Hola Mohalla, the whole region gathers, devotion, kirtan, and pure crowd energy.', 1);
insert into public.recommended_spots (district_slug, name, body, position) values ('una', 'Piplu Ridge (Bangana side)', 'One of Una’s best viewpoints, open sky, hill wind, and Gobind Sagar views. It’s quiet most days, and that’s what makes it special.', 2);
insert into public.recommended_spots (district_slug, name, body, position) values ('una', 'Shivbari Temple + Shiv Badi Forest (near Gagret/Amb)', 'This is a peaceful sacred spot surrounded by forest. Locals treat it with respect, keeping it quiet and calm. It’s perfect for a slow, silent visit.', 3);
insert into public.recommended_spots (district_slug, name, body, position) values ('una', 'Solah Singhi Fort ruins (Bangana)', 'A short hike (around 1 km) takes you to old stone walls, a hidden tank, and wide views. Not maintained like a tourist site, but that’s exactly why it feels real.', 4);
insert into public.recommended_spots (district_slug, name, body, position) values ('una', 'Unchha Pani (near Una town)', 'A simple local picnic spot, stream, shade, and families spending slow Sundays. No fancy setup, just a quiet day out as locals do.', 5);

